{% set name = "agg-regrid" %}
{% set version = "0.2.2" %}
{% set sha256 = "9aac13e714b7375481ea424f051951edf21897d933b6b3b01822796ea0fdf2ab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/SciTools-incubator/iris-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - cython
    - numpy 1.11.*
  run:
    - python
    - numpy >=1.11
    - iris

test:
  imports:
    - agg_regrid

about:
  home: https://github.com/SciTools-incubator/iris-{{ name }}
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: "A conservative area-weighted regridder that uses AGG to rasterise a source iris cube to a target grid"

extra:
  recipe-maintainers:
    - bjlittle
    - pelson
    - cpelley
