appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RQdMulD3B4Aym/fghoPwu+wpvu4On62R0HdjPteN+bAEw8JMCgJBW3Te7a/S78SJv19vN0T6faobVOiXXLFYa5Xa6XDx1fOyxUvi9ThLhLbfNpoV+TJ9eP58WfFUPoBpNTFpAjpK7knwonHEW4d+67RNP8ev/CBT541qnnmoE/vXWExQuY6+6ARWD5/BSn35cJIlvz8/S08HWEwnuUvKqXDTy2SjhqxD2JvDl3g2+bvJXrDEDNaiO5jzJRTSpJBYWsjR0SAGOi68+LO0E+aIR+C2MssGujO0G0ImPhoLoyQoE0E5l8tbWH4kXUTh76dgHPPxeVFwX8YizPniPcC3G35W4UTZdV5556iecK2O513DCBR4VUK+Yyv8++hLDep3r8uosisZNEqBUwnw1eGT6dc5V5AlhvsNuttwErBM2obhdbcZKVYL0+q0CgLybV2ssFwCuwUZrjzIYYu4XL8+8eSCrdHAJeB9rlXstMxtAzxb3K62wAi7I4Z3y9Y0ug7pUG/cKP7jgbpxmReEtPCnZymSXeNvFYte4aDLJmjb4YGVLpFCGPllmpmlktzBmXj3iknBjeynjf9JdWxt2G6aUaSE2ffPUSpc4fwvaVEvsdFvocacJFh0RZIqiz7mCOG/z+AhKKmErA6RR46cp5QMM1YEg9RaGBnbQXH4oNMk3OM=}
provider:
  win: azure
conda_forge_output_validation: false
